version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages
      - run: npm run build 
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages
      - run: npm run test
  lint:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint 
    
workflows:
  example-workflow:
    jobs:
      - build
      - test
      - lint
