version: 2.1
orbs:
  node: circleci/node@5.0.0
  npm-publisher: uraway/npm-publisher@0.2.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run test
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint

workflows:
  ci-build:
    jobs:
      - build
      - test
      - lint

  build_publish:
    jobs:
      - npm-publisher/publish-from-package-version:
          filters:
            branches:
              only: master
          pre-publish-steps:
            - run: npm ci
            - run: npm run build
          publish-token-variable: NPM_TOKEN
          push-git-tag: false
